name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip (native)
        run: sudo apt-get install zip -y

      - name: Create zip for Lambda
        run: |
          mkdir package
          cp -r src/* lambda_function.py package/       # Replace `src/` with your actual code folder
          cd package
          zip -r ../code.zip .

      - name: Deploy to Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-code \
              --function-name Today \
              --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
